name: Test ipv6

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ssh:
    name: Connection Test
    runs-on: ubuntu-latest

    steps:
      - name: ssh to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 2406:da12:1e4:2596:67d4:870c:c78:c502
          username: ec2-user
          key: ${{ secrets.KEY }}
          protocol: tcp6
          port: 22
          script: |
            whoami
