name: Test ipv6

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ssh:
    name: Connection Test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.1
        with:
          stack: dual

      - name: testing ipv6 for command
        run: |
          curl -m 9 --ipv6 --verbose https://google.com

      - name: test ipv6
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          protocol: tcp6
          port: 22
          command_timeout: 30s
          script: |
            whoami
