name: Test ipv6

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ssh:
    name: Connection Test
    runs-on: ubuntu-latest

    steps:
      - name: test ipv4
        uses: appleboy/ssh-action@master
        with:
          host: 52.78.103.215
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            whoami
            
      - name: test ipv6
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          protocol: tcp6
          port: 22
          command_timeout: 30s
          script: |
            whoami
